from app.schemas.blueprint import FeedbackMode, ProfessionDomain

LESSON_TEMPLATE_CATALOG = [
    {
        "id": "template-trainer-daily-flow",
        "lesson_type": "mixed",
        "title": "Trainer Daily Flow",
        "goal": "Повторить проблемную грамматику и встроить её в professional speaking.",
        "difficulty": "A2-B1",
        "estimated_duration": 25,
        "enabled_tracks": [ProfessionDomain.TRAINER_SKILLS.value],
        "generation_rules": [
            "Start with review or intro",
            "Finish with summary block",
            "Mix grammar, speaking and profession for daily lesson",
        ],
        "profession_topic_ids": ["topic-trainer-feedback"],
        "blocks": [
            {
                "id": "block-review-1",
                "position": 0,
                "block_type": "review_block",
                "title": "Review weak spots",
                "instructions": "Повтори ключевые исправления из прошлого урока.",
                "estimated_minutes": 4,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": [],
                "payload": {
                    "sourceMistakeIds": ["mistake-1"],
                    "reviewItems": [
                        "I have worked with this team since 2022.",
                        "This part could be clearer for the audience.",
                    ],
                    "targetErrorTypes": ["tense-choice", "feedback-language"],
                },
            },
            {
                "id": "block-grammar-1",
                "position": 1,
                "block_type": "grammar_block",
                "title": "Present Perfect in updates",
                "instructions": "Собери 3 коротких ответа о профессиональном опыте и недавних результатах.",
                "estimated_minutes": 6,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-review-1"],
                "payload": {
                    "topicId": "grammar-present-perfect-basics",
                    "focusPoints": ["experience", "recent results"],
                    "prompts": [
                        "Tell me what you have improved in your training process.",
                        "Describe what you have completed this month.",
                    ],
                    "targetErrorTypes": ["tense-choice"],
                },
            },
            {
                "id": "block-speaking-1",
                "position": 2,
                "block_type": "speaking_block",
                "title": "Guided speaking",
                "instructions": "Ответь на guided prompts и держи фокус на ясности.",
                "estimated_minutes": 7,
                "feedback_mode": FeedbackMode.CRITICAL_ONLY,
                "depends_on_block_ids": ["block-grammar-1"],
                "payload": {
                    "scenarioId": "training-debrief",
                    "mode": "guided",
                    "prompts": [
                        "How have you supported your learners recently?",
                        "What have your stakeholders asked for lately?",
                    ],
                    "expectsVoice": False,
                    "feedbackFocus": ["clarity", "tense consistency"],
                },
            },
            {
                "id": "block-profession-1",
                "position": 3,
                "block_type": "profession_block",
                "title": "Trainer feedback language",
                "instructions": "Смягчи жёсткие формулировки и сделай feedback естественнее.",
                "estimated_minutes": 5,
                "feedback_mode": FeedbackMode.IMMEDIATE,
                "depends_on_block_ids": ["block-speaking-1"],
                "payload": {
                    "domain": ProfessionDomain.TRAINER_SKILLS.value,
                    "topicId": "topic-trainer-feedback",
                    "scenario": "Post-workshop debrief",
                    "targetTerms": ["could", "clearer", "next step"],
                },
            },
            {
                "id": "block-summary-1",
                "position": 4,
                "block_type": "summary_block",
                "title": "Summary and next step",
                "instructions": "Зафиксируй правило, фразу и следующий шаг.",
                "estimated_minutes": 3,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-profession-1"],
                "payload": {
                    "recapPrompts": [
                        "What grammar point do you want to remember?",
                        "What phrase will you use tomorrow?",
                    ],
                    "nextStep": "Do a 5-minute /th/ pronunciation drill tomorrow.",
                    "saveToProgress": True,
                },
            },
        ],
    },
    {
        "id": "template-insurance-client-flow",
        "lesson_type": "mixed",
        "title": "Insurance Client Flow",
        "goal": "Отработать needs analysis, language of protection и уверенный follow-up после разговора с клиентом.",
        "difficulty": "A2-B1",
        "estimated_duration": 25,
        "enabled_tracks": [ProfessionDomain.INSURANCE.value],
        "generation_rules": [
            "Start with review or intro",
            "Finish with summary block",
            "Mix grammar, speaking and profession for daily lesson",
        ],
        "profession_topic_ids": ["topic-insurance-needs"],
        "blocks": [
            {
                "id": "block-insurance-review-1",
                "position": 0,
                "block_type": "review_block",
                "title": "Review client wording",
                "instructions": "Повтори ключевые исправления перед новым client update.",
                "estimated_minutes": 4,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": [],
                "payload": {
                    "sourceMistakeIds": ["mistake-seed-grammar", "mistake-seed-profession"],
                    "reviewItems": [
                        "We have reviewed your coverage needs this week.",
                        "Could we look at the protection options that fit your current plan?",
                    ],
                    "targetErrorTypes": ["tense-choice", "client-needs-language"],
                },
            },
            {
                "id": "block-insurance-grammar-1",
                "position": 1,
                "block_type": "grammar_block",
                "title": "Future forms for protection planning",
                "instructions": "Собери 3 коротких client-facing sentence о следующем шаге и coverage planning.",
                "estimated_minutes": 6,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-insurance-review-1"],
                "payload": {
                    "topicId": "grammar-future-forms-planning",
                    "focusPoints": ["next steps", "recommendations", "client follow-up"],
                    "prompts": [
                        "Explain what you will review before the next policy discussion.",
                        "Describe what you are going to send to the client after the call.",
                    ],
                    "targetErrorTypes": ["tense-choice"],
                },
            },
            {
                "id": "block-insurance-speaking-1",
                "position": 2,
                "block_type": "speaking_block",
                "title": "Guided client update",
                "instructions": "Ответь на guided prompts так, будто это короткий follow-up после needs analysis.",
                "estimated_minutes": 7,
                "feedback_mode": FeedbackMode.CRITICAL_ONLY,
                "depends_on_block_ids": ["block-insurance-grammar-1"],
                "payload": {
                    "scenarioId": "client-protection-follow-up",
                    "mode": "guided",
                    "prompts": [
                        "Summarize what protection need the client mentioned most clearly.",
                        "Explain the next action you will take after this conversation.",
                    ],
                    "expectsVoice": False,
                    "feedbackFocus": ["clarity", "next-step language", "confidence"],
                },
            },
            {
                "id": "block-insurance-profession-1",
                "position": 3,
                "block_type": "profession_block",
                "title": "Insurance needs analysis",
                "instructions": "Сделай формулировки мягкими, точными и понятными для клиента.",
                "estimated_minutes": 5,
                "feedback_mode": FeedbackMode.IMMEDIATE,
                "depends_on_block_ids": ["block-insurance-speaking-1"],
                "payload": {
                    "domain": ProfessionDomain.INSURANCE.value,
                    "topicId": "topic-insurance-needs",
                    "scenario": "Client discovery call",
                    "targetTerms": ["coverage", "protection", "next step"],
                },
            },
            {
                "id": "block-insurance-summary-1",
                "position": 4,
                "block_type": "summary_block",
                "title": "Summary and next client step",
                "instructions": "Зафиксируй одну удачную фразу, одно grammar правило и один next step.",
                "estimated_minutes": 3,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-insurance-profession-1"],
                "payload": {
                    "recapPrompts": [
                        "What client-friendly phrase do you want to keep?",
                        "What next-step sentence will you use tomorrow?",
                    ],
                    "nextStep": "Reuse one protection question and one follow-up sentence in the next client conversation.",
                    "saveToProgress": True,
                },
            },
        ],
    },
    {
        "id": "template-banking-client-flow",
        "lesson_type": "mixed",
        "title": "Banking Client Flow",
        "goal": "Потренировать product explanations, short updates по операциям и спокойный client-facing tone.",
        "difficulty": "A2-B1",
        "estimated_duration": 25,
        "enabled_tracks": [ProfessionDomain.BANKING.value],
        "generation_rules": [
            "Start with review or intro",
            "Finish with summary block",
            "Mix grammar, speaking and profession for daily lesson",
        ],
        "profession_topic_ids": ["topic-banking-product-explainer"],
        "blocks": [
            {
                "id": "block-banking-review-1",
                "position": 0,
                "block_type": "review_block",
                "title": "Review account update language",
                "instructions": "Повтори короткие исправления перед новым banking explanation.",
                "estimated_minutes": 4,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": [],
                "payload": {
                    "sourceMistakeIds": ["mistake-seed-grammar", "mistake-seed-profession"],
                    "reviewItems": [
                        "I have checked the payment status this morning.",
                        "Let me explain the transfer steps in a simpler way.",
                    ],
                    "targetErrorTypes": ["tense-choice", "banking-clarity-language"],
                },
            },
            {
                "id": "block-banking-grammar-1",
                "position": 1,
                "block_type": "grammar_block",
                "title": "Present Perfect in account updates",
                "instructions": "Собери 3 коротких banking update о статусе операции и recent changes.",
                "estimated_minutes": 6,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-banking-review-1"],
                "payload": {
                    "topicId": "grammar-past-simple-vs-present-perfect",
                    "focusPoints": ["recent updates", "client communication", "status checks"],
                    "prompts": [
                        "Explain what has changed in the account status today.",
                        "Describe what you have already checked before the next call.",
                    ],
                    "targetErrorTypes": ["tense-choice"],
                },
            },
            {
                "id": "block-banking-speaking-1",
                "position": 2,
                "block_type": "speaking_block",
                "title": "Guided banking explanation",
                "instructions": "Дай короткий spoken explanation о платеже, комиссии или следующем шаге.",
                "estimated_minutes": 7,
                "feedback_mode": FeedbackMode.CRITICAL_ONLY,
                "depends_on_block_ids": ["block-banking-grammar-1"],
                "payload": {
                    "scenarioId": "banking-product-clarifier",
                    "mode": "guided",
                    "prompts": [
                        "Explain one payment option in a calm and simple way.",
                        "Tell the client what will happen next after this check.",
                    ],
                    "expectsVoice": False,
                    "feedbackFocus": ["clarity", "structure", "client tone"],
                },
            },
            {
                "id": "block-banking-profession-1",
                "position": 3,
                "block_type": "profession_block",
                "title": "Banking product explainer",
                "instructions": "Упростить language around fees, transfers и account options.",
                "estimated_minutes": 5,
                "feedback_mode": FeedbackMode.IMMEDIATE,
                "depends_on_block_ids": ["block-banking-speaking-1"],
                "payload": {
                    "domain": ProfessionDomain.BANKING.value,
                    "topicId": "topic-banking-product-explainer",
                    "scenario": "Card and payment consultation",
                    "targetTerms": ["transfer", "fee", "statement"],
                },
            },
            {
                "id": "block-banking-summary-1",
                "position": 4,
                "block_type": "summary_block",
                "title": "Summary and next banking step",
                "instructions": "Зафиксируй одну ясную client phrase, одно grammar правило и один next step.",
                "estimated_minutes": 3,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-banking-profession-1"],
                "payload": {
                    "recapPrompts": [
                        "Which explanation sounded clearer this time?",
                        "What sentence will you reuse in the next client update?",
                    ],
                    "nextStep": "Reuse one short account-status update and one fee explanation in the next practice round.",
                    "saveToProgress": True,
                },
            },
        ],
    },
    {
        "id": "template-ai-business-flow",
        "lesson_type": "mixed",
        "title": "AI Business Flow",
        "goal": "Отработать объяснение AI workflow, limits, guardrails и следующего шага для бизнеса.",
        "difficulty": "A2-B1",
        "estimated_duration": 25,
        "enabled_tracks": [ProfessionDomain.AI_BUSINESS.value],
        "generation_rules": [
            "Start with review or intro",
            "Finish with summary block",
            "Mix grammar, speaking and profession for daily lesson",
        ],
        "profession_topic_ids": ["topic-ai-business-risk-brief"],
        "blocks": [
            {
                "id": "block-ai-review-1",
                "position": 0,
                "block_type": "review_block",
                "title": "Review AI workflow language",
                "instructions": "Повтори ключевые исправления перед новым AI workflow update.",
                "estimated_minutes": 4,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": [],
                "payload": {
                    "sourceMistakeIds": ["mistake-seed-grammar", "mistake-seed-profession"],
                    "reviewItems": [
                        "We have tested the workflow and added a human review step.",
                        "This automation can help, but we still need a clear approval path.",
                    ],
                    "targetErrorTypes": ["tense-choice", "risk-aware-language"],
                },
            },
            {
                "id": "block-ai-grammar-1",
                "position": 1,
                "block_type": "grammar_block",
                "title": "Present Perfect for AI updates",
                "instructions": "Собери 3 коротких update о том, что уже протестировано и что изменилось в workflow.",
                "estimated_minutes": 6,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-ai-review-1"],
                "payload": {
                    "topicId": "grammar-present-perfect-basics",
                    "focusPoints": ["recent experiments", "workflow updates", "results"],
                    "prompts": [
                        "Describe what you have already tested in the AI workflow.",
                        "Explain what has improved after the latest review.",
                    ],
                    "targetErrorTypes": ["tense-choice"],
                },
            },
            {
                "id": "block-ai-speaking-1",
                "position": 2,
                "block_type": "speaking_block",
                "title": "Guided AI project update",
                "instructions": "Дай short business update about an AI workflow and keep the explanation calm and concrete.",
                "estimated_minutes": 7,
                "feedback_mode": FeedbackMode.CRITICAL_ONLY,
                "depends_on_block_ids": ["block-ai-grammar-1"],
                "payload": {
                    "scenarioId": "ai-workflow-update",
                    "mode": "guided",
                    "prompts": [
                        "Summarize what the AI workflow now does well.",
                        "Explain one limit or control that still matters.",
                    ],
                    "expectsVoice": False,
                    "feedbackFocus": ["clarity", "business tone", "risk framing"],
                },
            },
            {
                "id": "block-ai-profession-1",
                "position": 3,
                "block_type": "profession_block",
                "title": "AI workflow briefing",
                "instructions": "Сделай language practical, risk-aware и понятным для business audience.",
                "estimated_minutes": 5,
                "feedback_mode": FeedbackMode.IMMEDIATE,
                "depends_on_block_ids": ["block-ai-speaking-1"],
                "payload": {
                    "domain": ProfessionDomain.AI_BUSINESS.value,
                    "topicId": "topic-ai-business-risk-brief",
                    "scenario": "AI workflow update",
                    "targetTerms": ["workflow", "guardrails", "review"],
                },
            },
            {
                "id": "block-ai-summary-1",
                "position": 4,
                "block_type": "summary_block",
                "title": "Summary and next workflow step",
                "instructions": "Зафиксируй одну clear phrase, один limit statement и один next step.",
                "estimated_minutes": 3,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-ai-profession-1"],
                "payload": {
                    "recapPrompts": [
                        "Which business-safe phrase sounded strongest?",
                        "What limit or control should stay in your next update?",
                    ],
                    "nextStep": "Reuse one workflow benefit sentence and one guardrail sentence in the next business explanation.",
                    "saveToProgress": True,
                },
            },
        ],
    },
    {
        "id": "template-cross-cultural-daily-flow",
        "lesson_type": "mixed",
        "title": "Everyday English Flow",
        "goal": "Укрепить everyday grammar, словарь и уверенное общение в понятных жизненных сценариях.",
        "difficulty": "A1-B1",
        "estimated_duration": 25,
        "enabled_tracks": [ProfessionDomain.CROSS_CULTURAL.value],
        "generation_rules": [
            "Start with review or intro",
            "Finish with summary block",
            "Mix grammar, speaking and vocabulary-rich communication for daily practice",
        ],
        "profession_topic_ids": ["topic-cross-cultural-everyday-communication"],
        "blocks": [
            {
                "id": "block-cross-cultural-review-1",
                "position": 0,
                "block_type": "review_block",
                "title": "Review useful phrases",
                "instructions": "Повтори короткие исправления перед новым everyday conversation.",
                "estimated_minutes": 4,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": [],
                "payload": {
                    "sourceMistakeIds": ["mistake-seed-grammar", "mistake-seed-profession"],
                    "reviewItems": [
                        "I have already tried that route before.",
                        "Could you help me with the next step, please?",
                    ],
                    "targetErrorTypes": ["tense-choice", "conversation-flow-language"],
                },
            },
            {
                "id": "block-cross-cultural-grammar-1",
                "position": 1,
                "block_type": "grammar_block",
                "title": "Present Perfect in real-life updates",
                "instructions": "Собери 3 коротких everyday answers про опыт, недавние действия и планы.",
                "estimated_minutes": 6,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-cross-cultural-review-1"],
                "payload": {
                    "topicId": "grammar-present-perfect-basics",
                    "focusPoints": ["experience", "recent actions", "daily confidence"],
                    "prompts": [
                        "Describe something you have already done this week.",
                        "Explain what you have learned recently in English.",
                    ],
                    "targetErrorTypes": ["tense-choice"],
                },
            },
            {
                "id": "block-cross-cultural-speaking-1",
                "position": 2,
                "block_type": "speaking_block",
                "title": "Guided everyday speaking",
                "instructions": "Ответь на короткие prompts так, будто это дружелюбный everyday conversation.",
                "estimated_minutes": 7,
                "feedback_mode": FeedbackMode.CRITICAL_ONLY,
                "depends_on_block_ids": ["block-cross-cultural-grammar-1"],
                "payload": {
                    "scenarioId": "speaking-everyday-check-in",
                    "mode": "guided",
                    "prompts": [
                        "Tell me about one thing you have enjoyed recently.",
                        "Ask one polite follow-up question to keep the conversation going.",
                    ],
                    "expectsVoice": False,
                    "feedbackFocus": ["clarity", "friendly tone", "confidence"],
                },
            },
            {
                "id": "block-cross-cultural-profession-1",
                "position": 3,
                "block_type": "profession_block",
                "title": "Everyday conversation builder",
                "instructions": "Сделай фразы дружелюбными, понятными и удобными для реального общения.",
                "estimated_minutes": 5,
                "feedback_mode": FeedbackMode.IMMEDIATE,
                "depends_on_block_ids": ["block-cross-cultural-speaking-1"],
                "payload": {
                    "domain": ProfessionDomain.CROSS_CULTURAL.value,
                    "topicId": "topic-cross-cultural-everyday-communication",
                    "scenario": "Daily conversation and travel check-in",
                    "targetTerms": ["could", "please", "next step"],
                },
            },
            {
                "id": "block-cross-cultural-summary-1",
                "position": 4,
                "block_type": "summary_block",
                "title": "Summary and next conversation step",
                "instructions": "Зафиксируй одну удобную фразу, одно правило и один next step.",
                "estimated_minutes": 3,
                "feedback_mode": FeedbackMode.AFTER_BLOCK,
                "depends_on_block_ids": ["block-cross-cultural-profession-1"],
                "payload": {
                    "recapPrompts": [
                        "What friendly phrase do you want to keep active?",
                        "What question will you reuse in the next conversation?",
                    ],
                    "nextStep": "Reuse one polite question and one recent-update sentence in the next short practice round.",
                    "saveToProgress": True,
                },
            },
        ],
    },
]
