from app.content.lessons.templates import (
    AI_BUSINESS_FLOW_TEMPLATE,
    BANKING_CLIENT_FLOW_TEMPLATE,
    CROSS_CULTURAL_DAILY_FLOW_TEMPLATE,
    INSURANCE_CLIENT_FLOW_TEMPLATE,
    TRAINER_DAILY_FLOW_TEMPLATE,
)


LESSON_TEMPLATE_CATALOG = [
    TRAINER_DAILY_FLOW_TEMPLATE,
    INSURANCE_CLIENT_FLOW_TEMPLATE,
    BANKING_CLIENT_FLOW_TEMPLATE,
    AI_BUSINESS_FLOW_TEMPLATE,
    CROSS_CULTURAL_DAILY_FLOW_TEMPLATE,
]
