from app.schemas.blueprint import FeedbackMode, ProfessionDomain


CROSS_CULTURAL_DAILY_FLOW_TEMPLATE = {
    "id": "template-cross-cultural-daily-flow",
    "lesson_type": "mixed",
    "title": "Everyday English Flow",
    "goal": "Укрепить everyday grammar, словарь и уверенное общение в понятных жизненных сценариях.",
    "difficulty": "A1-B1",
    "estimated_duration": 25,
    "enabled_tracks": [ProfessionDomain.CROSS_CULTURAL.value],
    "generation_rules": [
        "Start with review or intro",
        "Finish with summary block",
        "Mix grammar, speaking and vocabulary-rich communication for daily practice",
    ],
    "profession_topic_ids": ["topic-cross-cultural-everyday-communication"],
    "blocks": [
        {
            "id": "block-cross-cultural-review-1",
            "position": 0,
            "block_type": "review_block",
            "title": "Review useful phrases",
            "instructions": "Повтори короткие исправления перед новым everyday conversation.",
            "estimated_minutes": 4,
            "feedback_mode": FeedbackMode.AFTER_BLOCK,
            "depends_on_block_ids": [],
            "payload": {
                "sourceMistakeIds": ["mistake-seed-grammar", "mistake-seed-profession"],
                "reviewItems": [
                    "I have already tried that route before.",
                    "Could you help me with the next step, please?",
                ],
                "targetErrorTypes": ["tense-choice", "conversation-flow-language"],
            },
        },
        {
            "id": "block-cross-cultural-grammar-1",
            "position": 1,
            "block_type": "grammar_block",
            "title": "Present Perfect in real-life updates",
            "instructions": "Собери 3 коротких everyday answers про опыт, недавние действия и планы.",
            "estimated_minutes": 6,
            "feedback_mode": FeedbackMode.AFTER_BLOCK,
            "depends_on_block_ids": ["block-cross-cultural-review-1"],
            "payload": {
                "topicId": "grammar-present-perfect-basics",
                "focusPoints": ["experience", "recent actions", "daily confidence"],
                "prompts": [
                    "Describe something you have already done this week.",
                    "Explain what you have learned recently in English.",
                ],
                "targetErrorTypes": ["tense-choice"],
            },
        },
        {
            "id": "block-cross-cultural-speaking-1",
            "position": 2,
            "block_type": "speaking_block",
            "title": "Guided everyday speaking",
            "instructions": "Ответь на короткие prompts так, будто это дружелюбный everyday conversation.",
            "estimated_minutes": 7,
            "feedback_mode": FeedbackMode.CRITICAL_ONLY,
            "depends_on_block_ids": ["block-cross-cultural-grammar-1"],
            "payload": {
                "scenarioId": "speaking-everyday-check-in",
                "mode": "guided",
                "prompts": [
                    "Tell me about one thing you have enjoyed recently.",
                    "Ask one polite follow-up question to keep the conversation going.",
                ],
                "expectsVoice": False,
                "feedbackFocus": ["clarity", "friendly tone", "confidence"],
            },
        },
        {
            "id": "block-cross-cultural-profession-1",
            "position": 3,
            "block_type": "profession_block",
            "title": "Everyday conversation builder",
            "instructions": "Сделай фразы дружелюбными, понятными и удобными для реального общения.",
            "estimated_minutes": 5,
            "feedback_mode": FeedbackMode.IMMEDIATE,
            "depends_on_block_ids": ["block-cross-cultural-speaking-1"],
            "payload": {
                "domain": ProfessionDomain.CROSS_CULTURAL.value,
                "topicId": "topic-cross-cultural-everyday-communication",
                "scenario": "Daily conversation and travel check-in",
                "targetTerms": ["could", "please", "next step"],
            },
        },
        {
            "id": "block-cross-cultural-summary-1",
            "position": 4,
            "block_type": "summary_block",
            "title": "Summary and next conversation step",
            "instructions": "Зафиксируй одну удобную фразу, одно правило и один next step.",
            "estimated_minutes": 3,
            "feedback_mode": FeedbackMode.AFTER_BLOCK,
            "depends_on_block_ids": ["block-cross-cultural-profession-1"],
            "payload": {
                "recapPrompts": [
                    "What friendly phrase do you want to keep active?",
                    "What question will you reuse in the next conversation?",
                ],
                "nextStep": "Reuse one polite question and one recent-update sentence in the next short practice round.",
                "saveToProgress": True,
            },
        },
    ],
}
