from __future__ import annotations

from .types import TrackBaselineSpec


TRACK_BASELINES: dict[str, TrackBaselineSpec] = {
    "trainer_skills": {
        "template_id": "template-trainer-daily-flow",
        "grammar": {
            "subtype": "tense-choice",
            "source_module": "speaking",
            "original_text": "I work with this team since 2022.",
            "corrected_text": "I have worked with this team since 2022.",
            "explanation": "Нужен Present Perfect, потому что действие началось в прошлом и продолжается сейчас.",
            "repetition_count": 4,
        },
        "profession": {
            "subtype": "feedback-language",
            "source_module": "profession",
            "original_text": "This part is wrong.",
            "corrected_text": "This part could be clearer for the audience.",
            "explanation": "Для trainer context лучше использовать мягкие формулировки.",
            "repetition_count": 3,
        },
        "vocabulary": [
            {
                "code": "stakeholder",
                "word": "stakeholder",
                "translation": "заинтересованная сторона",
                "context": "Our stakeholders have asked for a shorter training format.",
                "category": "trainer_skills",
                "source_module": "profession",
                "review_reason": "Core trainer vocabulary to keep active in workshop updates.",
                "linked_mistake_subtype": "feedback-language",
                "linked_mistake_title": "Feedback language for workshops",
                "repetition_stage": 2,
            },
            {
                "code": "facilitation",
                "word": "facilitation",
                "translation": "фасилитация",
                "context": "Clear facilitation language keeps the workshop calm and structured.",
                "category": "trainer_skills",
                "source_module": "profession",
                "review_reason": "Useful trainer vocabulary for debrief and workshop structure.",
                "repetition_stage": 1,
            },
            {
                "code": "debrief",
                "word": "debrief",
                "translation": "разбор после сессии",
                "context": "We scheduled a short debrief after the session.",
                "category": "trainer_skills",
                "source_module": "speaking",
                "review_reason": "High-frequency workshop follow-up phrase.",
                "repetition_stage": 1,
            },
        ],
        "speaking_response": "I have improved the workshop opening, and I have added clearer examples for new managers.",
        "summary_response": "I need to keep Present Perfect active and use softer feedback after each training session.",
        "pronunciation": {
            "target_text": "thank the team for the thoughtful feedback",
            "transcript": "tank the team for the thoughtful feedback",
            "feedback": "The rhythm is stable, but /th/ still softens at the start of key words.",
            "weakest_words": ["thank", "thoughtful"],
            "focus_issues": ["/th/"],
        },
    },
    "insurance": {
        "template_id": "template-insurance-client-flow",
        "grammar": {
            "subtype": "future-form-choice",
            "source_module": "grammar",
            "original_text": "Tomorrow I discuss the coverage options with the client.",
            "corrected_text": "Tomorrow I am going to discuss the coverage options with the client.",
            "explanation": "Для запланированного следующего шага здесь лучше использовать future form с going to.",
            "repetition_count": 3,
        },
        "profession": {
            "subtype": "client-needs-language",
            "source_module": "profession",
            "original_text": "You need this policy because it is better.",
            "corrected_text": "Could we look at the protection options that fit your current needs?",
            "explanation": "В insurance dialogue лучше сначала уточнять потребность и мягко предлагать вариант.",
            "repetition_count": 3,
        },
        "vocabulary": [
            {
                "code": "coverage",
                "word": "coverage",
                "translation": "страховое покрытие",
                "context": "We reviewed the coverage options before the next client call.",
                "category": "insurance",
                "source_module": "profession",
                "review_reason": "Core client-facing insurance vocabulary.",
                "linked_mistake_subtype": "client-needs-language",
                "linked_mistake_title": "Client needs analysis language",
                "repetition_stage": 2,
            },
            {
                "code": "premium",
                "word": "premium",
                "translation": "страховая премия",
                "context": "The client asked how the premium could change next year.",
                "category": "insurance",
                "source_module": "profession",
                "review_reason": "Useful for follow-up explanations after needs analysis.",
                "repetition_stage": 1,
            },
            {
                "code": "claim",
                "word": "claim",
                "translation": "страховой случай / претензия",
                "context": "I explained what documents are needed for a claim.",
                "category": "insurance",
                "source_module": "speaking",
                "review_reason": "High-frequency insurance support term.",
                "repetition_stage": 1,
            },
        ],
        "speaking_response": "We are going to review the client's protection needs and send a short follow-up summary after the call.",
        "summary_response": "I need cleaner next-step language and softer phrasing when I explain protection options.",
        "pronunciation": {
            "target_text": "three thoughtful themes for client protection",
            "transcript": "free thoughtful themes for client protection",
            "feedback": "The sentence is understandable, but /th/ still shifts toward /f/ in the opening phrase.",
            "weakest_words": ["three", "themes"],
            "focus_issues": ["/th/"],
        },
    },
    "banking": {
        "template_id": "template-banking-client-flow",
        "grammar": {
            "subtype": "tense-choice",
            "source_module": "speaking",
            "original_text": "I checked the transfer today and I sent the update now.",
            "corrected_text": "I have checked the transfer today and I have already sent the update.",
            "explanation": "Когда важен текущий результат банковского апдейта, нужен Present Perfect.",
            "repetition_count": 3,
        },
        "profession": {
            "subtype": "banking-clarity-language",
            "source_module": "profession",
            "original_text": "This fee is normal, so just use this option.",
            "corrected_text": "Let me explain the fee difference and show which option fits this transfer better.",
            "explanation": "В banking English лучше объяснять выбор и benefit, а не давать резкое указание.",
            "repetition_count": 3,
        },
        "vocabulary": [
            {
                "code": "transfer",
                "word": "transfer",
                "translation": "перевод",
                "context": "I checked the transfer status before calling the client back.",
                "category": "banking",
                "source_module": "profession",
                "review_reason": "Core banking support vocabulary.",
                "linked_mistake_subtype": "banking-clarity-language",
                "linked_mistake_title": "Banking product clarity",
                "repetition_stage": 2,
            },
            {
                "code": "statement",
                "word": "statement",
                "translation": "выписка",
                "context": "The client asked how to read the latest statement.",
                "category": "banking",
                "source_module": "profession",
                "review_reason": "Common banking explanation term.",
                "repetition_stage": 1,
            },
            {
                "code": "fee",
                "word": "fee",
                "translation": "комиссия",
                "context": "I explained the fee difference in a calmer way.",
                "category": "banking",
                "source_module": "speaking",
                "review_reason": "Useful for product and payment explanations.",
                "repetition_stage": 1,
            },
        ],
        "speaking_response": "I have checked the payment status, and I can explain the next transfer step in a simpler way now.",
        "summary_response": "I need clearer client-friendly phrases when I explain transfer options and fees.",
        "pronunciation": {
            "target_text": "thank the client and clarify the transfer",
            "transcript": "tank the client and clarify the transfer",
            "feedback": "The main idea is clear, but the opening /th/ still drops too quickly.",
            "weakest_words": ["thank"],
            "focus_issues": ["/th/"],
        },
    },
    "ai_business": {
        "template_id": "template-ai-business-flow",
        "grammar": {
            "subtype": "tense-choice",
            "source_module": "writing",
            "original_text": "We tested the workflow this week and now it saves time for the team.",
            "corrected_text": "We have tested the workflow this week, and now it saves time for the team.",
            "explanation": "Для недавнего AI experiment с актуальным результатом здесь лучше подходит Present Perfect.",
            "repetition_count": 3,
        },
        "profession": {
            "subtype": "risk-aware-language",
            "source_module": "profession",
            "original_text": "The AI tool is safe, so we can automate everything.",
            "corrected_text": "The AI tool helps with the draft, but we still need a human review step.",
            "explanation": "Для business AI communication важно оставлять guardrails и human review в формулировке.",
            "repetition_count": 3,
        },
        "vocabulary": [
            {
                "code": "workflow",
                "word": "workflow",
                "translation": "рабочий процесс",
                "context": "We have improved the workflow after the latest review cycle.",
                "category": "ai_business",
                "source_module": "profession",
                "review_reason": "Core AI business explanation term.",
                "linked_mistake_subtype": "risk-aware-language",
                "linked_mistake_title": "Risk-aware AI explanations",
                "repetition_stage": 2,
            },
            {
                "code": "guardrail",
                "word": "guardrail",
                "translation": "ограничитель / safeguard",
                "context": "This guardrail keeps the AI draft inside the approved workflow.",
                "category": "ai_business",
                "source_module": "profession",
                "review_reason": "Important for safe AI process language.",
                "repetition_stage": 1,
            },
            {
                "code": "approval",
                "word": "approval",
                "translation": "согласование",
                "context": "We still need an approval step before the final send.",
                "category": "ai_business",
                "source_module": "writing",
                "review_reason": "Useful in AI implementation updates and process notes.",
                "repetition_stage": 1,
            },
        ],
        "speaking_response": "We have tested the workflow, and we still keep a human review step before the final output.",
        "summary_response": "I need risk-aware wording so the AI update sounds useful, practical, and safe for business.",
        "pronunciation": {
            "target_text": "this workflow still needs a thoughtful review",
            "transcript": "dis workflow still needs a thoughtful review",
            "feedback": "The message is clear, but /th/ and sentence stress still need a cleaner contrast.",
            "weakest_words": ["this", "thoughtful"],
            "focus_issues": ["/th/", "sentence stress"],
        },
    },
    "cross_cultural": {
        "template_id": "template-cross-cultural-daily-flow",
        "grammar": {
            "subtype": "tense-choice",
            "source_module": "speaking",
            "original_text": "I already try this route before.",
            "corrected_text": "I have already tried this route before.",
            "explanation": "Для недавнего опыта и результата в настоящем здесь лучше подходит Present Perfect.",
            "repetition_count": 3,
        },
        "profession": {
            "subtype": "conversation-flow-language",
            "source_module": "profession",
            "original_text": "Tell me where is the station.",
            "corrected_text": "Could you tell me where the station is, please?",
            "explanation": "Для everyday conversation лучше использовать более вежливый и естественный вопрос.",
            "repetition_count": 3,
        },
        "vocabulary": [
            {
                "code": "direction",
                "word": "direction",
                "translation": "направление / маршрут",
                "context": "I asked for directions before the next stop.",
                "category": "cross_cultural",
                "source_module": "profession",
                "review_reason": "Useful everyday vocabulary for travel and daily communication.",
                "linked_mistake_subtype": "conversation-flow-language",
                "linked_mistake_title": "Everyday conversation flow",
                "repetition_stage": 2,
            },
            {
                "code": "schedule",
                "word": "schedule",
                "translation": "расписание / план",
                "context": "We checked the schedule before the next visit.",
                "category": "cross_cultural",
                "source_module": "speaking",
                "review_reason": "Helpful for everyday planning and school-friendly communication.",
                "repetition_stage": 1,
            },
            {
                "code": "question",
                "word": "question",
                "translation": "вопрос",
                "context": "I asked one more question to keep the conversation going.",
                "category": "cross_cultural",
                "source_module": "speaking",
                "review_reason": "High-frequency word for daily interaction practice.",
                "repetition_stage": 1,
            },
        ],
        "speaking_response": "I have practiced a few useful phrases, and I can ask a clearer question now.",
        "summary_response": "I need to keep polite questions and simple recent-update sentences active in daily English.",
        "pronunciation": {
            "target_text": "thank them for the thoughtful directions",
            "transcript": "tank them for the thoughtful directions",
            "feedback": "The sentence is easy to follow, but /th/ still needs a cleaner start in common everyday phrases.",
            "weakest_words": ["thank", "thoughtful"],
            "focus_issues": ["/th/"],
        },
    },
}
