import type { Lesson, LessonRecommendation } from "../../entities/lesson/model";
import type { Mistake, WeakSpot } from "../../entities/mistake/model";
import type { ProgressSnapshot } from "../../entities/progress/model";
import { defaultOnboardingAnswers, type UserProfile } from "../../entities/user/model";
import type {
  DailyLoopPlan,
  DiagnosticRoadmap,
  DashboardData,
  GrammarTopic,
  LearnerJourneyState,
  ProfessionTrackCard,
  PronunciationDrill,
  ProviderStatus,
  QuickAction,
  SpeakingScenario,
  WritingTask,
} from "../types/app-data";
import { routes } from "../constants/routes";

export const mockProfile: UserProfile = {
  id: "user-local-1",
  name: "Alex",
  nativeLanguage: "ru",
  currentLevel: "A2",
  targetLevel: "B2",
  professionTrack: "cross_cultural",
  preferredUiLanguage: "ru",
  preferredExplanationLanguage: "ru",
  lessonDuration: 25,
  speakingPriority: 8,
  grammarPriority: 7,
  professionPriority: 5,
  onboardingAnswers: {
    ...defaultOnboardingAnswers,
    primaryGoal: "everyday_communication",
    learningContext: "general_english",
    interestTopics: ["daily_life", "travel", "stories"],
  },
};

export const mockProgress: ProgressSnapshot = {
  id: "progress-1",
  grammarScore: 54,
  speakingScore: 48,
  listeningScore: 42,
  pronunciationScore: 40,
  writingScore: 51,
  professionScore: 46,
  regulationScore: 18,
  streak: 6,
  dailyGoalMinutes: 25,
  minutesCompletedToday: 12,
  history: [
    {
      id: "lesson-history-1",
      title: "Present Perfect and Work Updates",
      lessonType: "mixed",
      completedAt: "2026-03-19",
      score: 74,
    },
    {
      id: "lesson-history-2",
      title: "Trainer Feedback Language",
      lessonType: "professional",
      completedAt: "2026-03-18",
      score: 69,
    },
  ],
};

export const mockWeakSpots: WeakSpot[] = [
  {
    id: "weak-1",
    title: "Present Perfect vs Past Simple",
    category: "grammar",
    recommendation: "Нужен короткий review + speaking drill на опыт и недавние действия.",
  },
  {
    id: "weak-2",
    title: "Sound /th/",
    category: "pronunciation",
    recommendation: "Добавить 5 минут shadowing и minimal pairs.",
  },
  {
    id: "weak-3",
    title: "Feedback language for workshops",
    category: "profession",
    recommendation: "Повторить мягкие формулировки для фасилитации и coaching.",
  },
];

export const mockRecommendation: LessonRecommendation = {
  id: "lesson-recommendation-1",
  title: "Daily Mixed Lesson: Grammar + Speaking + Trainer English",
  lessonType: "mixed",
  goal: "Укрепить Present Perfect и потренировать trainer feedback language.",
  duration: 25,
  focusArea: "grammar,speaking,profession",
};

export const mockQuickActions: QuickAction[] = [
  {
    id: "action-1",
    title: "Grammar Sprint",
    description: "10 минут на ключевую тему и быстрый drill.",
    route: routes.grammar,
  },
  {
    id: "action-2",
    title: "Speaking Check-in",
    description: "Короткий guided speaking с фидбеком.",
    route: routes.speaking,
  },
  {
    id: "action-3",
    title: "Profession Hub",
    description: "Профессиональный английский по текущему треку.",
    route: routes.profession,
  },
];

export const mockDailyLoopPlan: DailyLoopPlan = {
  id: "daily-loop-1",
  planDateKey: "2026-04-13",
  status: "planned",
  stage: "first_path",
  sessionKind: "recommended",
  focusArea: "speaking",
  headline: "Alex, your first guided daily loop is ready.",
  summary:
    "Start from speaking confidence, reinforce grammar in context, and let the system shape tomorrow's next best step from one connected session.",
  whyThisNow:
    "The proof lesson and onboarding both point to a voice-led start, so the first loop keeps the path simple and immediately useful.",
  nextStepHint: "Open today's loop, finish the first guided session, and then review the updated next step.",
  preferredMode: "voice_first",
  timeBudgetMinutes: 25,
  estimatedMinutes: 24,
  recommendedLessonType: "mixed",
  recommendedLessonTitle: "First Guided Daily Loop",
  lessonRunId: null,
  completedAt: null,
  steps: [
    {
      id: "warm-start",
      skill: "coach",
      title: "Warm start",
      description: "Liza frames the session and explains why this is the right move today.",
      durationMinutes: 2,
    },
    {
      id: "vocabulary-recall",
      skill: "vocabulary",
      title: "Vocabulary recall",
      description: "Bring back a few words that the next speaking response will need.",
      durationMinutes: 3,
    },
    {
      id: "response",
      skill: "speaking",
      title: "Speaking response",
      description: "Answer one guided prompt and convert correction into a stronger version.",
      durationMinutes: 6,
    },
  ],
  ritual: {
    headline: "First guided daily ritual",
    promise:
      "One connected daily ritual around speaking that opens with guidance, moves through active practice, and closes with an explicit next step.",
    completionRule:
      "The ritual is only complete after the final strategic summary closes the route and updates the next step.",
    closureRule:
      "Open today's loop, finish the first guided session, and then review the updated next step.",
    stages: [
      {
        id: "warm-start",
        title: "Warm start",
        summary: "Liza frames the route and explains why today matters now.",
        emphasis: "entry",
        required: true,
      },
      {
        id: "vocabulary-recall",
        title: "Vocabulary recall",
        summary: "Bring back a few words that the next response will need right away.",
        emphasis: "memory",
        required: true,
      },
      {
        id: "response",
        title: "Speaking response",
        summary: "Answer one guided prompt and convert correction into a stronger version.",
        emphasis: "output",
        required: true,
      },
      {
        id: "summary",
        title: "Strategic summary",
        summary: "Name what moved, what still needs watching, and what the next step should be.",
        emphasis: "closure",
        required: true,
      },
    ],
  },
  taskDrivenInput: {
    inputRoute: "/listening",
    inputLabel: "listening input",
    responseRoute: "/speaking",
    responseLabel: "spoken response",
    title: "Audio signal mission",
    summary: "Take one useful audio signal from the guided daily loop, convert it into a clearer spoken response, and return it to the route around speaking.",
    bridge: "After the input pass, move the signal into spoken response before returning to the wider route.",
    closure: "The mission closes only after the spoken response feeds the next connected route step.",
  },
};

export const mockJourneyState: LearnerJourneyState = {
  userId: "user-local-1",
  stage: "daily_loop_ready",
  source: "proof_lesson",
  preferredMode: "voice_first",
  diagnosticReadiness: "soft_start",
  timeBudgetMinutes: 25,
  currentFocusArea: "speaking",
  currentStrategySummary:
    "The current strategy starts from speaking confidence, then reinforces grammar and vocabulary inside one connected daily ritual.",
  nextBestAction:
    "Finish today's guided loop, review the result summary, and let tomorrow's route sharpen around the same signal.",
  lastDailyPlanId: "daily-loop-1",
  strategySnapshot: {
    focusArea: "speaking",
    primaryGoal: "everyday_communication",
    sessionSummary: {
      outcomeBand: "stable",
      headline: "This session kept the route stable.",
      whatWorked: "Speaking response gave the system enough confidence to keep the main route connected instead of rebuilding it from zero.",
      watchSignal: "The system should still watch Present Perfect vs Past Simple so the same weak pattern does not reappear in the next route.",
      strategyShift: "Tomorrow stays centered on grammar while keeping a light watch on Present Perfect vs Past Simple.",
      coachNote: "This is the moment to keep the ritual going and let the next route sharpen naturally.",
      carryOverSignalLabel: "Speaking response",
      watchSignalLabel: "Present Perfect vs Past Simple",
      weakSpotTitle: "Present Perfect vs Past Simple",
      strongestSignalLabel: "Speaking response",
      weakestSignalLabel: "Grammar pattern",
      practiceMixEvaluation: {
        leadPracticeKey: "speaking",
        leadPracticeTitle: "Speaking practice",
        leadOutcome: "held",
        leadAverageScore: 82,
        strongestPracticeKey: "speaking",
        strongestPracticeTitle: "Speaking practice",
        strongestPracticeScore: 82,
        weakestPracticeKey: "grammar",
        weakestPracticeTitle: "Grammar patterning",
        weakestPracticeScore: 68,
        summaryLine: "Speaking practice carried the route best, while grammar patterning still needs support in the next session.",
      },
    },
    tomorrowPreview: {
      focusArea: "grammar",
      sessionKind: "recommended",
      headline: "Tomorrow returns with a guided grammar-led loop.",
      reason: "The next route narrows a little so the corrected speaking signal can become more stable.",
      nextStepHint: "Come back tomorrow and start from the guided grammar-led loop.",
      recommendedLessonTitle: "Tomorrow Guided Loop",
      continuityMode: "guided",
      carryOverSignalLabel: "Speaking response",
      watchSignalLabel: "Present Perfect vs Past Simple",
    },
    skillTrajectory: {
      focusSkill: "pronunciation",
      direction: "slipping",
      summary: "Across the last 3 snapshots, pronunciation has been slipping, so the route keeps extra support there.",
      observedSnapshots: 3,
      signals: [
        {
          skill: "pronunciation",
          direction: "slipping",
          deltaScore: -7,
          currentScore: 46,
          summary: "pronunciation has dropped from 53 to 46 across recent sessions, so the route should give it steadier support.",
        },
        {
          skill: "grammar",
          direction: "stable",
          deltaScore: 1,
          currentScore: 52,
          summary: "grammar is still hovering around 52/100 across recent sessions, so the route should keep it warm instead of treating it as solved.",
        },
      ],
    },
    strategyMemory: {
      focusSkill: "grammar",
      persistenceLevel: "recurring",
      summary: "Across the last 5 snapshots, grammar keeps resurfacing as a recurring weak area, so the route keeps protecting it beyond one session.",
      observedSnapshots: 5,
      signals: [
        {
          skill: "grammar",
          persistenceLevel: "recurring",
          averageScore: 54,
          latestScore: 52,
          lowHits: 4,
          summary: "grammar kept resurfacing in 4 of the last 5 snapshots, so the route should revisit it deliberately instead of assuming it is already stable.",
        },
        {
          skill: "pronunciation",
          persistenceLevel: "emerging",
          averageScore: 49,
          latestScore: 46,
          lowHits: 3,
          summary: "pronunciation is beginning to drift into longer-term pressure, so the route should keep it in view before it becomes the main blocker.",
        },
      ],
    },
    routeCadenceMemory: {
      status: "steady_return",
      observedPlans: 5,
      completedPlans: 4,
      missedPlans: 0,
      idleDays: 1,
      summary: "Recent route history shows a steady return rhythm, so the next step can stay crisp and forward-moving.",
      actionHint: "Keep the ritual moving with a clear next step instead of restarting from zero.",
    },
    routeRecoveryMemory: {
      phase: "support_reopen_arc",
      horizonDays: 2,
      focusSkill: "writing",
      supportPracticeTitle: "Writing support",
      sessionShape: "guided_balance",
      summary: "Writing support has already returned once inside the connected route, so the next pass should settle it before the route widens.",
      actionHint: "Give writing support one more connected pass, then let the wider route reopen again.",
      nextPhaseHint: "If this second reopen pass holds, the route can widen after that without another protected reset.",
      reopenTargetLabel: "writing support",
      reopenTargetRoute: routes.writing,
      reopenReady: true,
      reopenStage: "settling_back_in",
      reopenDayCount: 1,
      expansionReady: false,
    },
    routeReentryProgress: {
      sequenceKey: "route-reentry:user-local-1:daily-loop-1:skill_repair_cycle:grammar",
      phase: "skill_repair_cycle",
      focusSkill: "grammar",
      orderedRoutes: [routes.grammar, routes.writing, routes.speaking, routes.vocabulary, routes.pronunciation],
      completedRoutes: [routes.grammar],
      nextRoute: routes.writing,
      status: "active",
    },
    routeEntryMemory: {
      recentEntries: [
        {
          route: routes.dailyLoop,
          source: "surface_visit",
          enteredAt: "2026-04-15T08:10:00",
          stage: "daily_loop_ready",
          recoveryPhase: "skill_repair_cycle",
          sessionShape: "focused_support",
          nextRoute: routes.writing,
        },
        {
          route: routes.writing,
          source: "smart_reentry",
          enteredAt: "2026-04-16T08:14:00",
          stage: "daily_loop_ready",
          recoveryPhase: "skill_repair_cycle",
          sessionShape: "focused_support",
          nextRoute: routes.writing,
        },
      ],
      lastRoute: routes.writing,
      lastSource: "smart_reentry",
      repeatedRouteCount: 1,
      activeNextRoute: routes.writing,
      activeNextRouteVisits: 2,
      connectedResetVisits: 2,
      readyToReopenActiveNextRoute: true,
    },
    routeFollowUpMemory: {
      currentRoute: routes.writing,
      currentLabel: "writing support",
      followUpRoute: routes.dailyLoop,
      followUpLabel: "daily route",
      stageLabel: "Settling pass",
      status: "active",
      summary: "The route should reopen through writing support first, then flow back into the connected daily route.",
    },
    learningBlueprint: {
      version: "v1",
      generatedAt: "2026-04-18T08:10:00",
      headline: "Alex's learning blueprint",
      northStar:
        "Move from A2 toward B1 by making everyday communication feel usable through a connected route led by speaking.",
      strategicSummary:
        "The current strategy starts from speaking confidence, then reinforces grammar and vocabulary inside one connected daily ritual.",
      learnerSnapshot:
        "adult self learner in general english, prefers voice first study and 25-minute sessions.",
      routeMode: "guided balance · voice_first · full",
      currentPhase: "support_reopen_arc",
      currentPhaseLabel: "Support reopen arc",
      currentFocus: "speaking",
      successSignal:
        "The route should reopen through writing support first, then flow back into the connected daily route.",
      lizaRole:
        "Liza should protect the reopen arc, explain why speaking still leads, and keep the learner from treating support work as a separate product.",
      focusPillars: [
        {
          id: "goal",
          title: "Goal-led route",
          reason: "The route should keep serving everyday communication instead of splitting into disconnected drills.",
          source: "onboarding_goal",
        },
        {
          id: "focus",
          title: "Speaking leads first",
          reason: "Speaking is the current lead signal, so the route should organize the next session around it before widening to adjacent skills.",
          source: "current_focus",
        },
        {
          id: "recovery",
          title: "Recovery arc protection",
          reason: "Writing support has already returned once inside the connected route, so the next pass should settle it before the route widens.",
          source: "route_recovery_memory",
        },
      ],
      checkpoints: [
        {
          id: "today",
          title: "Land today's route cleanly",
          summary: "Finish today's guided loop, review the result summary, and let tomorrow's route sharpen around the same signal.",
          successSignal: "The route stays coherent around speaking instead of breaking into detached modules.",
        },
        {
          id: "follow-up",
          title: "Open daily route",
          summary: "The route should reopen through writing support first, then flow back into the connected daily route.",
          successSignal: "The learner should see one obvious step after the current surface rather than needing to guess.",
        },
      ],
      rhythmContract: [
        "Keep sessions around 18 minutes so the route stays repeatable.",
        "Use voice first as the default lane unless the recovery arc needs a calmer shape.",
        "Give writing support one more connected pass, then let the wider route reopen again.",
      ],
      guardrails: [
        "Do not fragment the day into unrelated drills.",
        "Keep speaking visible as the lead signal before widening.",
        "Feedback should stay calm and corrective, not overwhelming.",
        "Every harder step should still come with a clear example or anchor.",
      ],
    },
  },
  onboardingCompletedAt: "2026-04-13T10:10:00",
  createdAt: "2026-04-13T10:10:00",
  updatedAt: "2026-04-13T10:10:00",
};

export const mockDashboardData: DashboardData = {
  profile: mockProfile,
  progress: mockProgress,
  weakSpots: mockWeakSpots,
  recommendation: mockRecommendation,
  dailyLoopPlan: mockDailyLoopPlan,
  journeyState: mockJourneyState,
  studyLoop: {
    focusArea: "grammar",
    headline: "Alex, today's adaptive focus is grammar.",
    summary:
      "Start from Present Perfect vs Past Simple, keep the daily chain moving, and clear 1 vocabulary review item. Minutes completed today: 12.",
    recommendation: mockRecommendation,
    weakSpots: mockWeakSpots.slice(0, 2),
    dueVocabulary: [
      {
        id: "vocab-1",
        word: "stakeholder",
        translation: "заинтересованная сторона",
        context: "Our stakeholders have asked for a shorter training format.",
        category: "trainer_skills",
        sourceModule: "seed",
        reviewReason: "Core vocabulary practice for the current profession track.",
        linkedMistakeSubtype: null,
        linkedMistakeTitle: null,
        learnedStatus: "active",
        repetitionStage: 2,
        dueNow: true,
      },
    ],
    vocabularyBacklinks: [
      {
        weakSpotTitle: "Present Perfect vs Past Simple",
        weakSpotCategory: "grammar",
        dueCount: 1,
        activeCount: 2,
        exampleWords: ["I have worked", "already sent"],
        sourceModules: ["speaking", "writing"],
      },
    ],
    mistakeResolution: [
      {
        weakSpotTitle: "Present Perfect vs Past Simple",
        weakSpotCategory: "grammar",
        status: "recovering",
        repetitionCount: 4,
        lastSeenDaysAgo: 2,
        linkedVocabularyCount: 2,
        resolutionHint: "The pattern is still being reviewed, but it is appearing less often in fresh corrections.",
      },
      {
        weakSpotTitle: "Feedback language for workshops",
        weakSpotCategory: "profession",
        status: "active",
        repetitionCount: 3,
        lastSeenDaysAgo: 1,
        linkedVocabularyCount: 0,
        resolutionHint: "This weak spot is still repeating often enough that it should stay in active recovery.",
      },
    ],
    moduleRotation: [
      {
        moduleKey: "speaking",
        title: "Speaking refresh",
        reason: "Short guided speaking keeps the corrected pattern active without forcing a full recovery loop.",
        route: routes.speaking,
        priority: 1,
      },
      {
        moduleKey: "vocabulary",
        title: "Vocabulary repetition",
        reason: "Review 1 due item before the next larger module.",
        route: routes.vocabulary,
        priority: 2,
      },
      {
        moduleKey: "lesson",
        title: "Return to the main lesson flow",
        reason: "Use the broader lesson track to keep corrected patterns alive in context.",
        route: routes.lessonRunner,
        priority: 3,
      },
    ],
    vocabularySummary: {
      dueCount: 1,
      newCount: 0,
      activeCount: 1,
      masteredCount: 0,
      weakestCategory: "trainer_skills",
    },
    listeningFocus: "audio_comprehension",
    generationRationale: [
      "Primary weak spot: Present Perfect vs Past Simple.",
      "Listening support added for audio comprehension.",
      "Vocabulary queue has 1 due item.",
      "Most overloaded vocabulary category: trainer_skills.",
      "Next lesson generation is recovery-first.",
    ],
    nextSteps: [
      {
        id: "step-1",
        title: "Recover your main weak spot",
        description: "Open a focused drill for grammar and fix the repeated pattern.",
        route: routes.grammar,
        stepType: "recovery",
      },
      {
        id: "step-2",
        title: "Review due vocabulary",
        description: "Repeat 1 word before the next full lesson block.",
        route: routes.activity,
        stepType: "vocabulary",
      },
      {
        id: "step-3",
        title: "Continue with the recommended lesson",
        description: "Move forward after recovery so the app keeps pushing the long-term track ahead.",
        route: routes.lessonRunner,
        stepType: "lesson",
      },
    ],
    strategyAlignment: {
      focusArea: "grammar",
      routeTitle: "Adaptive Recovery Loop",
      routeSeedSource: "daily_loop_plan",
      routeSeedDetail: "The current route still protects repeated repair work while it prepares the next wider lesson.",
      whyNow: "Recovery pressure is easing, but the route still needs one clear signal to stay stable before it broadens.",
      nextBestAction: "Start with the guided route and then support the weakest live signal before widening again.",
      carryOverSignalLabel: "Speaking response",
      watchSignalLabel: "Present Perfect vs Past Simple",
      recommendedModuleKey: "grammar",
      recommendedModuleReason: "Keep the route structurally stable while the recovery pressure continues to soften.",
      liveProgressFocus: "pronunciation",
      liveProgressScore: 46,
      liveProgressReason: "Fresh progress is currently weakest in pronunciation, so the adaptive route is leaning there before it widens again.",
      skillTrajectory: {
        focusSkill: "pronunciation",
        direction: "slipping",
        summary: "Across the last 3 snapshots, pronunciation has been slipping, so the route keeps extra support there.",
        observedSnapshots: 3,
        signals: [
          {
            skill: "pronunciation",
            direction: "slipping",
            deltaScore: -7,
            currentScore: 46,
            summary: "pronunciation has dropped from 53 to 46 across recent sessions, so the route should give it steadier support.",
          },
        ],
      },
      strategyMemory: {
        focusSkill: "grammar",
        persistenceLevel: "recurring",
        summary: "Across the last 5 snapshots, grammar keeps resurfacing as a recurring pressure point, so the route keeps it inside the longer strategy instead of treating it as a one-off.",
        observedSnapshots: 5,
        signals: [
          {
            skill: "grammar",
            persistenceLevel: "recurring",
            averageScore: 54,
            latestScore: 52,
            lowHits: 4,
            summary: "grammar stayed under pressure often enough across the last 5 snapshots that the route should keep returning there deliberately.",
          },
          {
            skill: "pronunciation",
            persistenceLevel: "emerging",
            averageScore: 49,
            latestScore: 46,
            lowHits: 3,
            summary: "pronunciation is drifting across the longer memory, so the route keeps it visible even when another module is leading today.",
          },
        ],
      },
      routeCadenceMemory: {
        status: "gentle_reentry",
        observedPlans: 5,
        completedPlans: 3,
        missedPlans: 1,
        idleDays: 2,
        summary: "The learner is returning after a short break, so the route should reopen calmly before it asks for more range.",
        actionHint: "Use a calmer restart and let the route earn momentum again instead of jumping straight into pressure.",
      },
      routeRecoveryMemory: {
        phase: "protected_return",
        horizonDays: 2,
        focusSkill: "grammar",
        supportPracticeTitle: "Speaking practice",
        sessionShape: "protected_mix",
        summary: "The route is back in motion, but the next 2 sessions should still protect grammar before opening fully.",
        actionHint: "Use a protected return for the next 2 routes and let Speaking practice carry some of the load.",
        nextPhaseHint: "If the return rhythm holds, the route can widen again after these protected sessions.",
      },
      routeReentryFocus: "writing",
      routeReentryNextRoute: routes.writing,
      routeReentryNextLabel: "writing support",
      routeReentryCompletedSteps: 1,
      routeReentryTotalSteps: 5,
    },
  },
  quickActions: mockQuickActions,
  resumeLesson: null,
};

export const mockDiagnosticRoadmap: DiagnosticRoadmap = {
  declaredCurrentLevel: "A2",
  estimatedLevel: "A2",
  targetLevel: "B2",
  overallScore: 43,
  summary:
    "Roadmap towards B2: strengthen pronunciation and listening first, then convert recovery work into longer lesson gains. Immediate focus: Present Perfect vs Past Simple, Sound /th/.",
  weakestSkills: ["pronunciation", "listening", "profession English"],
  nextFocus: ["Present Perfect vs Past Simple", "Sound /th/"],
  milestones: [
    {
      level: "A2",
      status: "current",
      readiness: 100,
      requiredScore: 35,
      currentScore: 43,
      description: "Stabilize everyday grammar, short speaking turns and basic work vocabulary.",
      focusSkills: ["pronunciation", "listening"],
    },
    {
      level: "B1",
      status: "upcoming",
      readiness: 83,
      requiredScore: 52,
      currentScore: 43,
      description: "Build longer explanations, better time control and more reliable listening coverage.",
      focusSkills: ["pronunciation", "listening"],
    },
    {
      level: "B2",
      status: "upcoming",
      readiness: 61,
      requiredScore: 70,
      currentScore: 43,
      description: "Push fluency, nuanced feedback language and confident professional communication.",
      focusSkills: ["pronunciation", "listening"],
    },
  ],
};

export const mockLesson: Lesson = {
  id: "lesson-1",
  lessonType: "mixed",
  title: "Trainer Daily Flow",
  goal: "Повторить проблемную грамматику и встроить её в professional speaking.",
  difficulty: "A2-B1",
  duration: 25,
  modules: [
    "review_block",
    "grammar_block",
    "speaking_block",
    "profession_block",
    "summary_block",
  ],
  completed: false,
  blocks: [
    {
      id: "block-1",
      blockType: "review_block",
      title: "Review weak spots",
      instructions: "Посмотри на частые ошибки и повтори правильные паттерны.",
      estimatedMinutes: 4,
      payload: {
        items: [
          "I have worked with teams from 2021.",
          "I have already sent the workshop notes.",
        ],
      },
    },
    {
      id: "block-2",
      blockType: "grammar_block",
      title: "Present Perfect in professional updates",
      instructions: "Собери 3 коротких ответа про опыт и недавние результаты.",
      estimatedMinutes: 6,
      payload: {
        prompts: [
          "Tell me what projects you have completed this month.",
          "Explain what you have learned as a trainer recently.",
        ],
      },
    },
    {
      id: "block-3",
      blockType: "speaking_block",
      title: "Guided speaking",
      instructions: "Ответь устно или текстом на 2 guided prompts.",
      estimatedMinutes: 7,
      payload: {
        prompts: [
          "How have you improved your training sessions lately?",
          "What have your learners asked for this quarter?",
        ],
      },
    },
    {
      id: "block-4",
      blockType: "profession_block",
      title: "Trainer feedback language",
      instructions: "Смягчи обратную связь и сделай её более естественной.",
      estimatedMinutes: 5,
      payload: {
        phrases: [
          "Let's tighten the structure a little.",
          "Your example is useful, but we can make it clearer for beginners.",
        ],
      },
    },
    {
      id: "block-5",
      blockType: "summary_block",
      title: "Summary and next step",
      instructions: "Зафиксируй 1 правило, 1 фразу и 1 навык на завтра.",
      estimatedMinutes: 3,
      payload: {
        nextStep: "Завтра сделать pronunciation mini-session на /th/.",
      },
    },
  ],
};

export const mockDiagnosticLesson: Lesson = {
  id: "lesson-diagnostic-1",
  lessonType: "diagnostic",
  title: "Checkpoint Diagnostic: A2 -> B2",
  goal: "Проверить grammar, speaking, listening и writing и обновить roadmap.",
  difficulty: "A2-B2",
  duration: 20,
  modules: ["grammar_block", "speaking_block", "listening_block", "writing_block", "summary_block"],
  completed: false,
  blocks: [
    {
      id: "diagnostic-block-1",
      blockType: "grammar_block",
      title: "Grammar checkpoint",
      instructions: "Answer two short grammar prompts.",
      estimatedMinutes: 5,
      payload: { prompts: ["Use present perfect in a work update.", "Fix one incorrect sentence."] },
    },
    {
      id: "diagnostic-block-2",
      blockType: "speaking_block",
      title: "Speaking checkpoint",
      instructions: "Give one structured answer about your progress.",
      estimatedMinutes: 5,
      payload: { prompts: ["Summarize your recent learning progress."] },
    },
    {
      id: "diagnostic-block-3",
      blockType: "listening_block",
      title: "Listening checkpoint",
      instructions: "Read the transcript and answer the questions.",
      estimatedMinutes: 4,
      payload: { transcript: "I have updated the training deck for new managers.", questions: ["What was updated?"] },
    },
    {
      id: "diagnostic-block-4",
      blockType: "writing_block",
      title: "Writing checkpoint",
      instructions: "Write a concise professional reply.",
      estimatedMinutes: 4,
      payload: { brief: "Reply to a teammate and confirm next steps." },
    },
    {
      id: "diagnostic-block-5",
      blockType: "summary_block",
      title: "Checkpoint summary",
      instructions: "Note the strongest and weakest skill.",
      estimatedMinutes: 2,
      payload: { nextStep: "Open refreshed roadmap." },
    },
  ],
};

export const mockGrammarTopics: GrammarTopic[] = [
  {
    id: "grammar-1",
    title: "Present Perfect Basics",
    level: "A2-B1",
    mastery: 58,
    explanation: "Используй для опыта, недавних действий и результата в настоящем.",
    checkpoints: ["have/has + V3", "already / yet / just", "experience"],
  },
  {
    id: "grammar-2",
    title: "Past Simple vs Present Perfect",
    level: "A2-B1",
    mastery: 43,
    explanation: "Past Simple = finished time. Present Perfect = result or experience.",
    checkpoints: ["finished time markers", "experience questions", "recent updates"],
  },
  {
    id: "grammar-3",
    title: "Future Forms for Planning",
    level: "A2-B1",
    mastery: 61,
    explanation: "be going to, will и present continuous для планов и решений.",
    checkpoints: ["plans", "promises", "schedule"],
  },
];

export const mockSpeakingScenarios: SpeakingScenario[] = [
  {
    id: "speaking-1",
    title: "Daily Stand-up",
    mode: "guided",
    goal: "Рассказывать о прогрессе коротко и уверенно.",
    prompt: "Share what you have completed, what you are doing next, and one blocker.",
    feedbackHint: "Сделай акцент на времени и результатах.",
  },
  {
    id: "speaking-2",
    title: "Training Debrief",
    mode: "roleplay",
    goal: "Давать мягкий feedback after workshop.",
    prompt: "Explain what went well and what should improve before the next session.",
    feedbackHint: "Используй softer language: could, might, let's.",
  },
];

export const mockPronunciationDrills: PronunciationDrill[] = [
  {
    id: "pronunciation-1",
    title: "Soft /th/ control",
    sound: "/th/",
    focus: "Уменьшить русскую замену на /z/ и /s/.",
    phrases: ["thank the team", "three thoughtful themes", "this method works"],
    difficulty: "A2-B1",
  },
  {
    id: "pronunciation-2",
    title: "Sentence stress",
    sound: "stress",
    focus: "Усилить смысловые слова в коротких рабочих фразах.",
    phrases: ["I HAVE updated the module", "We NEED a clearer example"],
    difficulty: "A2-B1",
  },
];

export const mockWritingTask: WritingTask = {
  id: "writing-1",
  title: "Reply to a hiring manager",
  brief: "Напиши короткий ответ с благодарностью, интересом к роли и готовностью обсудить детали.",
  tone: "professional and warm",
  checklist: [
    "thank the person",
    "show interest",
    "offer next step",
    "keep it concise",
  ],
  improvedVersionPreview:
    "Thank you for reaching out. I would be glad to discuss the role in more detail and share how my training background could support the team.",
};

export const mockProfessionTracks: ProfessionTrackCard[] = [
  {
    id: "track-1",
    title: "Insurance English",
    domain: "insurance",
    summary: "Клиентские разговоры, продукты, objections и needs analysis.",
    lessonFocus: ["client conversations", "value communication", "customer protection"],
  },
  {
    id: "track-2",
    title: "Banking English",
    domain: "banking",
    summary: "Базовая лексика по продуктам, платежам и retail banking.",
    lessonFocus: ["payments", "cards", "financial conversations"],
  },
  {
    id: "track-3",
    title: "Trainer Skills",
    domain: "trainer_skills",
    summary: "Язык фасилитации, coaching, структурирование тренинга и feedback.",
    lessonFocus: ["facilitation", "feedback language", "coaching language"],
  },
  {
    id: "track-4",
    title: "AI for Business",
    domain: "ai_business",
    summary: "AI workflows, prompts, limitations и объяснение кейсов на английском.",
    lessonFocus: ["prompts", "AI assistants", "risk-aware explanations"],
  },
  {
    id: "track-5",
    title: "Everyday Communication",
    domain: "cross_cultural",
    summary: "Повседневный английский, поездки, дружелюбные разговорные сценарии и school-safe practice.",
    lessonFocus: ["daily conversations", "travel confidence", "friendly communication"],
  },
];

export const mockMistakes: Mistake[] = [
  {
    id: "mistake-1",
    category: "grammar",
    subtype: "tense-choice",
    sourceModule: "speaking",
    originalText: "I work with this team since 2022.",
    correctedText: "I have worked with this team since 2022.",
    explanation: "Нужен Present Perfect, потому что действие началось в прошлом и продолжается сейчас.",
    repetitionCount: 4,
    lastSeenAt: "2026-03-19T18:15:00",
  },
  {
    id: "mistake-2",
    category: "pronunciation",
    subtype: "th-sound",
    sourceModule: "pronunciation",
    originalText: "sink",
    correctedText: "think",
    explanation: "Нужно вывести язык слегка между зубами и не заменять звук на /s/.",
    repetitionCount: 6,
    lastSeenAt: "2026-03-20T11:30:00",
  },
  {
    id: "mistake-3",
    category: "profession",
    subtype: "feedback-language",
    sourceModule: "profession",
    originalText: "This part is wrong.",
    correctedText: "This part could be clearer for the audience.",
    explanation: "Для trainer context лучше использовать мягкие формулировки.",
    repetitionCount: 3,
    lastSeenAt: "2026-03-19T18:19:00",
  },
];

export const mockProviderStatus: ProviderStatus[] = [
  {
    key: "mock_llm",
    name: "Fallback LLM",
    type: "llm",
    status: "mock",
    details: "Local fallback responses stay available during development and whenever LM Studio is unavailable.",
  },
  {
    key: "stt_bridge",
    name: "STT Bridge",
    type: "stt",
    status: "offline",
    details: "Подключение не настроено, предусмотрен graceful degradation.",
  },
  {
    key: "tts_bridge",
    name: "TTS Bridge",
    type: "tts",
    status: "offline",
    details: "Пока не активирован, UI должен работать без озвучки.",
  },
  {
    key: "scoring_engine",
    name: "Scoring Engine",
    type: "scoring",
    status: "mock",
    details: "Базовая оценка готова к замене на rule-based или AI scoring.",
  },
];
